import { z } from 'zod';

/** RFC 4122 UUID, used for every server-generated identifier. */
export const uuidSchema = z.string().uuid();

/** ISO-8601 timestamp in UTC, always serialised with a `Z` suffix. */
export const timestampSchema = z.string().datetime({ offset: false });

/** Lowercase hex SHA-256 digest — exactly 64 hex characters. */
export const sha256Schema = z
  .string()
  .regex(/^[0-9a-f]{64}$/, 'must be a lowercase hex SHA-256 digest');

/**
 * Correlation identifier echoed on every response and written to the audit log.
 * Generated by the API when the caller does not supply one.
 */
export const requestIdSchema = z.string().min(8).max(64);

/** Health of a single subsystem as reported by `/api/system/status`. */
export const componentStatusSchema = z.enum([
  'ok',
  'degraded',
  'down',
  'unknown',
  /** The component requires a manual credential step that has not been done. */
  'manual_configuration_required',
]);
export type ComponentStatus = z.infer<typeof componentStatusSchema>;

export const componentReportSchema = z.object({
  /** Stable machine key, e.g. `postgres`. */
  id: z.string().min(1).max(64),
  /** Human label for the dashboard card. */
  label: z.string().min(1).max(120),
  status: componentStatusSchema,
  /** Short human-readable explanation. Never contains secret material. */
  detail: z.string().max(500),
  /** Round-trip latency of the probe, when one was performed. */
  latencyMs: z.number().nonnegative().optional(),
  checkedAt: timestampSchema,
});
export type ComponentReport = z.infer<typeof componentReportSchema>;

export type Timestamp = z.infer<typeof timestampSchema>;
export type Uuid = z.infer<typeof uuidSchema>;
export type Sha256 = z.infer<typeof sha256Schema>;

/** Uniform body for every `DELETE` endpoint across the API. */
export const deletedResponseSchema = z.object({ deleted: z.literal(true) });
export type DeletedResponse = z.infer<typeof deletedResponseSchema>;
