import { useCallback, useEffect, useState } from 'react';
import type { ProjectRoadmapResponse, RoadmapMilestone, RoadmapPriority, RoadmapStatus, TaskDetailResponse } from '@project-control/contracts';
import { ApiError, api } from '../../api-client';

const statusLabel=(status:RoadmapStatus)=>status.replace('_',' ');
const statuses:RoadmapStatus[]=['planned','in_progress','blocked','done','cancelled'];
const priorities:RoadmapPriority[]=['low','medium','high','critical'];
const allowedTransitions:Record<RoadmapStatus,RoadmapStatus[]>={planned:['in_progress','blocked','cancelled'],in_progress:['blocked','done','cancelled'],blocked:['in_progress','planned','cancelled'],done:['in_progress','planned'],cancelled:['planned']};
const statusOptions=(current:RoadmapStatus)=>[current,...allowedTransitions[current]];

export function RoadmapView({projectId,canWrite,archived,onSessionExpired}:{projectId:string;canWrite:boolean;archived:boolean;onSessionExpired:()=>void}):React.JSX.Element{
  const [roadmap,setRoadmap]=useState<ProjectRoadmapResponse|null>(null);const [activity,setActivity]=useState<Array<{id:string;label:string;occurredAt:string}>>([]);
  const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [showAdd,setShowAdd]=useState(false);const [selectedTask,setSelectedTask]=useState<string|null>(null);
  const writable=canWrite&&!archived&&!roadmap?.readOnly;
  const handleError=useCallback((caught:unknown)=>{if(caught instanceof ApiError){if(caught.isAuthFailure){onSessionExpired();return;}setError(caught.message);}else setError('The roadmap request failed.');},[onSessionExpired]);
  const load=useCallback(async(signal?:AbortSignal)=>{try{const [data,history]=await Promise.all([api.getRoadmap(projectId,signal),api.getRoadmapActivity(projectId)]);setRoadmap(data);setActivity(history.entries);setError(null);}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;handleError(e);}},[projectId,handleError]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load]);
  async function run(action:()=>Promise<unknown>){setBusy(true);setError(null);try{await action();await load();}catch(e){handleError(e);}finally{setBusy(false);}}
  if(!roadmap)return <p>{error??'Loading roadmap…'}</p>;
  if(selectedTask)return <TaskDetail projectId={projectId} taskId={selectedTask} writable={Boolean(writable)} onBack={()=>{setSelectedTask(null);void load();}} onError={handleError}/>;
  return <section aria-labelledby="roadmap-heading" className="roadmap-view">
    <div className="card-head"><div><h2 id="roadmap-heading">Roadmap</h2><strong>{roadmap.progress.completed} / {roadmap.progress.total} tasks complete · {roadmap.progress.percentage}%</strong></div>{writable&&<button className="primary" type="button" onClick={()=>setShowAdd(!showAdd)}>+ Add milestone</button>}</div>
    {(archived||roadmap.readOnly)&&<div className="alert alert-warn" role="status">This project is archived. Roadmap changes are disabled.</div>}
    {error&&<div className="alert alert-error" role="alert">{error}</div>}
    {showAdd&&writable&&<MilestoneForm busy={busy} onCancel={()=>setShowAdd(false)} onSubmit={(body)=>run(async()=>{await api.createMilestone(projectId,body);setShowAdd(false);})}/>}
    {roadmap.milestones.length===0?<article className="card roadmap-empty"><strong>No milestones yet.</strong><span className="hint">Add the first milestone to start this manual roadmap.</span></article>:roadmap.milestones.map((milestone,index)=><MilestoneCard key={milestone.id} milestone={milestone} projectId={projectId} writable={Boolean(writable)} first={index===0} last={index===roadmap.milestones.length-1} busy={busy} onRun={run} onOpenTask={setSelectedTask}/>) }
    <article className="card"><span className="card-title">Roadmap activity</span>{activity.length===0?<p className="hint">No roadmap activity yet.</p>:<ul className="roadmap-activity">{activity.map(entry=><li key={entry.id}><span>{entry.label}</span><time dateTime={entry.occurredAt}>{new Date(entry.occurredAt).toLocaleString()}</time></li>)}</ul>}</article>
  </section>;
}

function MilestoneForm({initial,busy,onCancel,onSubmit}:{initial?:RoadmapMilestone;busy:boolean;onCancel:()=>void;onSubmit:(body:any)=>Promise<void>|void}){
  const [title,setTitle]=useState(initial?.title??'');const [description,setDescription]=useState(initial?.description??'');const [status,setStatus]=useState<RoadmapStatus>(initial?.status??'planned');const [priority,setPriority]=useState<RoadmapPriority>(initial?.priority??'medium');const [targetDate,setTargetDate]=useState(initial?.targetDate??'');const [blockedReason,setBlockedReason]=useState(initial?.blockedReason??'');
  const suffix=initial?.id??'new';
  return <form className="card roadmap-form" onSubmit={(e)=>{e.preventDefault();void onSubmit({title:title.trim(),description,status,priority,targetDate:targetDate||null,...(status==='blocked'?{blockedReason:blockedReason.trim()}: {})});}}><div className="field"><label htmlFor={`milestone-title-${suffix}`}>Title *</label><input id={`milestone-title-${suffix}`} required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field"><label htmlFor={`milestone-description-${suffix}`}>Description</label><textarea id={`milestone-description-${suffix}`} rows={2} value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="form-row">{!initial&&<div className="field"><label htmlFor={`milestone-status-${suffix}`}>Status</label><select id={`milestone-status-${suffix}`} value={status} onChange={e=>setStatus(e.target.value as RoadmapStatus)}>{statuses.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></div>}<div className="field"><label htmlFor={`milestone-priority-${suffix}`}>Priority</label><select id={`milestone-priority-${suffix}`} value={priority} onChange={e=>setPriority(e.target.value as RoadmapPriority)}>{priorities.map(p=><option key={p}>{p}</option>)}</select></div><div className="field"><label htmlFor={`milestone-date-${suffix}`}>Target date</label><input id={`milestone-date-${suffix}`} type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)}/></div></div>{!initial&&status==='blocked'&&<div className="field"><label htmlFor={`milestone-reason-${suffix}`}>Block reason *</label><textarea id={`milestone-reason-${suffix}`} required value={blockedReason} onChange={e=>setBlockedReason(e.target.value)}/></div>}<div className="roadmap-actions"><button className="primary" disabled={busy||!title.trim()}>Save</button><button type="button" disabled={busy} onClick={onCancel}>Cancel</button></div></form>;
}

function MilestoneCard({milestone,projectId,writable,first,last,busy,onRun,onOpenTask}:{milestone:RoadmapMilestone;projectId:string;writable:boolean;first:boolean;last:boolean;busy:boolean;onRun:(fn:()=>Promise<unknown>)=>Promise<void>;onOpenTask:(id:string)=>void}){
  const [expanded,setExpanded]=useState(true);const [editing,setEditing]=useState(false);const [addingTask,setAddingTask]=useState(false);const inactive=Boolean(milestone.archivedAt)||milestone.status==='cancelled';
  async function setStatus(status:RoadmapStatus){let blockedReason:string|undefined;if(status==='blocked'){blockedReason=window.prompt('Block reason *')?.trim();if(!blockedReason)return;}await onRun(()=>api.changeMilestoneStatus(projectId,milestone.id,{status,...(blockedReason?{blockedReason}: {})}));}
  return <article className={`card milestone-card ${inactive?'roadmap-inactive':''}`}><div className="card-head"><button className="roadmap-expand" type="button" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'▾':'▸'} <span className="card-title">{milestone.title}</span></button><span className="badge badge-unknown">{statusLabel(milestone.status)}</span></div><div className="roadmap-progress"><progress value={milestone.progress.completed} max={Math.max(1,milestone.progress.total)} aria-label={`${milestone.progress.percentage}% complete`}/><span>{milestone.progress.completed} / {milestone.progress.total} tasks · {milestone.progress.percentage}%</span></div>{milestone.progress.total>0&&milestone.progress.completed===milestone.progress.total&&<p className="hint">All tasks are complete.</p>}{milestone.blockedReason&&<p className="alert alert-warn">Blocked: {milestone.blockedReason}</p>}{milestone.targetDate&&<p className="card-meta">Target: {milestone.targetDate} · Priority: {milestone.priority}</p>}
    {writable&&<div className="roadmap-actions">{!inactive&&<><button disabled={busy||first} aria-label={`Move ${milestone.title} up`} onClick={()=>void onRun(()=>api.reorderMilestone(projectId,milestone.id,'up'))}>↑</button><button disabled={busy||last} aria-label={`Move ${milestone.title} down`} onClick={()=>void onRun(()=>api.reorderMilestone(projectId,milestone.id,'down'))}>↓</button></>}{milestone.archivedAt?<button disabled={busy} onClick={()=>void onRun(()=>api.reactivateMilestone(projectId,milestone.id))}>Reactivate</button>:<>{!inactive&&<button disabled={busy} onClick={()=>setEditing(!editing)}>Edit</button>}<select disabled={busy} aria-label={`Change ${milestone.title} status`} value={milestone.status} onChange={e=>void setStatus(e.target.value as RoadmapStatus)}>{statusOptions(milestone.status).map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select><button disabled={busy} onClick={()=>void onRun(()=>api.archiveMilestone(projectId,milestone.id))}>Archive</button></>}</div>}
    {editing&&!inactive&&<MilestoneForm initial={milestone} busy={busy} onCancel={()=>setEditing(false)} onSubmit={async(body)=>{await onRun(()=>api.updateMilestone(projectId,milestone.id,{title:body.title,description:body.description,priority:body.priority,targetDate:body.targetDate}));setEditing(false);}}/>}
    {expanded&&<div className="roadmap-tasks">{milestone.tasks.length===0?<p className="hint">No tasks in this milestone.</p>:milestone.tasks.map((task,index)=><div className="roadmap-task-row" key={task.id}><button className="task-open" onClick={()=>onOpenTask(task.id)}><span aria-hidden="true">{task.status==='done'?'✓':task.status==='blocked'?'!':task.status==='in_progress'?'→':'○'}</span><span>{task.title}</span><small>{statusLabel(task.status)}{task.nextAction?` · Next: ${task.nextAction}`:''}</small></button>{writable&&!inactive&&<span className="roadmap-order"><button disabled={index===0} aria-label={`Move ${task.title} up`} onClick={()=>void onRun(()=>api.reorderRoadmapTask(projectId,task.id,'up'))}>↑</button><button disabled={index===milestone.tasks.length-1} aria-label={`Move ${task.title} down`} onClick={()=>void onRun(()=>api.reorderRoadmapTask(projectId,task.id,'down'))}>↓</button></span>}</div>)}{writable&&!inactive&&(addingTask?<TaskCreate busy={busy} onCancel={()=>setAddingTask(false)} onSubmit={async body=>{await onRun(()=>api.createRoadmapTask(projectId,milestone.id,body));setAddingTask(false);}}/>:<button type="button" onClick={()=>setAddingTask(true)}>+ Add task</button>)}</div>}
  </article>;
}

function TaskCreate({busy,onCancel,onSubmit}:{busy:boolean;onCancel:()=>void;onSubmit:(body:any)=>Promise<void>}){const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [priority,setPriority]=useState<RoadmapPriority>('medium');const [status,setStatus]=useState<'planned'|'in_progress'|'done'|'cancelled'>('planned');return <form className="roadmap-form" onSubmit={e=>{e.preventDefault();void onSubmit({title:title.trim(),description,priority,status});}}><div className="field"><label htmlFor="new-task-title">Task title *</label><input id="new-task-title" required value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field"><label htmlFor="new-task-description">Description</label><textarea id="new-task-description" value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="form-row"><select aria-label="Task priority" value={priority} onChange={e=>setPriority(e.target.value as RoadmapPriority)}>{priorities.map(p=><option key={p}>{p}</option>)}</select><select aria-label="Task status" value={status} onChange={e=>setStatus(e.target.value as typeof status)}>{['planned','in_progress','done','cancelled'].map(s=><option key={s}>{s}</option>)}</select></div><div className="roadmap-actions"><button className="primary" disabled={busy}>Add task</button><button type="button" onClick={onCancel}>Cancel</button></div></form>}

function TaskDetail({projectId,taskId,writable,onBack,onError}:{projectId:string;taskId:string;writable:boolean;onBack:()=>void;onError:(e:unknown)=>void}){
  const [detail,setDetail]=useState<TaskDetailResponse|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [criterion,setCriterion]=useState('');const [note,setNote]=useState('');const [dependency,setDependency]=useState('');
  const fail=useCallback((e:unknown)=>{setError(e instanceof ApiError?e.message:'The task request failed.');onError(e);},[onError]);
  const load=useCallback(async()=>{try{setDetail((await api.getRoadmapTask(projectId,taskId)).detail);setError(null);}catch(e){fail(e);}},[projectId,taskId,fail]);useEffect(()=>{void load();},[load]);
  async function run(fn:()=>Promise<{detail:TaskDetailResponse}>){setBusy(true);setError(null);try{setDetail((await fn()).detail);}catch(e){fail(e);}finally{setBusy(false);}}
  async function confirmedStatus(statusValue:RoadmapStatus){let blockedReason:string|undefined;if(statusValue==='blocked'){blockedReason=window.prompt('Block reason *')?.trim();if(!blockedReason)return;}setBusy(true);setError(null);try{let response;try{response=await api.changeRoadmapTaskStatus(projectId,taskId,{status:statusValue,...(blockedReason?{blockedReason}: {})});}catch(e){if(!(e instanceof ApiError)||e.code!=='confirmation_required'||!e.confirmation)throw e;const message=e.confirmation.kind==='incomplete_acceptance'?`${e.confirmation.count} acceptance criteria are incomplete. Complete task anyway?`:`${e.confirmation.count} dependencies are not completed. Start task anyway?`;if(!window.confirm(message))return;response=await api.changeRoadmapTaskStatus(projectId,taskId,{status:statusValue,...(blockedReason?{blockedReason}: {}),acknowledgeIncompleteAcceptance:e.confirmation.kind==='incomplete_acceptance',acknowledgeIncompleteDependencies:e.confirmation.kind==='incomplete_dependencies'});}setDetail(response.detail);}catch(e){fail(e);}finally{setBusy(false);}}
  if(!detail)return <section><button onClick={onBack}>← Back to roadmap</button>{error?<div className="alert alert-error" role="alert">{error}</div>:<p>Loading task…</p>}</section>;const task=detail.task;
  return <section className="task-detail"><button onClick={onBack}>← Back to roadmap</button>{error&&<div className="alert alert-error" role="alert">{error}</div>}<article className="card"><div className="card-head"><h2>{task.title}</h2><span className="badge badge-unknown">{statusLabel(task.status)}</span></div><p>{task.description||'No description.'}</p><p className="card-meta">Priority: {task.priority} · Created: {new Date(task.createdAt).toLocaleString()} · Started: {task.startedAt?new Date(task.startedAt).toLocaleString():'not started'} · Completed: {task.completedAt?new Date(task.completedAt).toLocaleString():'not completed'}</p>{task.blockedReason&&<div className="alert alert-warn">Blocked: {task.blockedReason}</div>}{writable&&<><TaskEdit detail={detail} busy={busy} onSave={body=>run(()=>api.updateRoadmapTask(projectId,taskId,body))}/><div className="field"><label htmlFor="task-status">Status</label><select id="task-status" value={task.status} onChange={e=>void confirmedStatus(e.target.value as RoadmapStatus)} disabled={busy}>{statusOptions(task.status).map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select></div></>}</article>
    <article className="card"><span className="card-title">Acceptance criteria</span>{detail.criteria.map((item,index)=><div className="check-row" key={item.id}><input type="checkbox" checked={item.isCompleted} aria-label={`${item.isCompleted?'Reopen':'Complete'} ${item.text}`} disabled={!writable||busy} onChange={()=>void run(()=>api.completeCriterion(projectId,taskId,item.id,!item.isCompleted))}/><span>{item.text}</span>{writable&&<span className="roadmap-order"><button disabled={busy||index===0} aria-label={`Move ${item.text} up`} onClick={()=>void run(()=>api.reorderCriterion(projectId,taskId,item.id,'up'))}>↑</button><button disabled={busy||index===detail.criteria.length-1} aria-label={`Move ${item.text} down`} onClick={()=>void run(()=>api.reorderCriterion(projectId,taskId,item.id,'down'))}>↓</button><button disabled={busy} aria-label={`Edit ${item.text}`} onClick={()=>{const text=window.prompt('Edit criterion',item.text)?.trim();if(text)void run(()=>api.updateCriterion(projectId,taskId,item.id,text));}}>Edit</button><button disabled={busy} aria-label={`Delete ${item.text}`} onClick={()=>void run(()=>api.deleteCriterion(projectId,taskId,item.id))}>Delete</button></span>}</div>)}{writable&&<form className="inline-add" onSubmit={e=>{e.preventDefault();if(criterion.trim())void run(async()=>{const result=await api.addCriterion(projectId,taskId,criterion.trim());setCriterion('');return result;});}}><label className="visually-hidden" htmlFor="new-criterion">New criterion</label><input id="new-criterion" value={criterion} onChange={e=>setCriterion(e.target.value)} placeholder="Add acceptance criterion"/><button disabled={busy}>Add</button></form>}</article>
    <article className="card"><span className="card-title">Dependencies</span>{detail.dependencies.length===0?<p className="hint">No dependencies.</p>:detail.dependencies.map(dep=><div className="check-row" key={dep.dependsOnTaskId}><span aria-hidden="true">{dep.resolved?'✓':'○'}</span><span>{dep.title} — {dep.status}{dep.status==='cancelled'?' (unresolved/cancelled)':''}</span>{writable&&<button disabled={busy} aria-label={`Remove dependency ${dep.title}`} onClick={()=>void run(()=>api.removeDependency(projectId,taskId,dep.dependsOnTaskId))}>Remove</button>}</div>)}{writable&&<form className="inline-add" onSubmit={e=>{e.preventDefault();if(dependency)void run(async()=>{const result=await api.addDependency(projectId,taskId,dependency);setDependency('');return result;});}}><label htmlFor="dependency-select">Add dependency</label><select id="dependency-select" value={dependency} onChange={e=>setDependency(e.target.value)}><option value="">Select a task</option>{detail.dependencyCandidates.map(c=><option key={c.id} value={c.id}>{c.title} ({c.status})</option>)}</select><button disabled={busy||!dependency}>Add</button></form>}</article>
    <article className="card"><span className="card-title">Notes</span>{detail.notes.length===0?<p className="hint">No notes.</p>:detail.notes.map(item=><div className="note" key={item.id}><p>{item.body}</p><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString()}</time>{writable&&<span><button onClick={()=>{const body=window.prompt('Edit note',item.body)?.trim();if(body)void run(()=>api.updateNote(projectId,taskId,item.id,body));}}>Edit</button><button onClick={()=>void run(()=>api.deleteNote(projectId,taskId,item.id))}>Delete</button></span>}</div>)}{writable&&<form className="field" onSubmit={e=>{e.preventDefault();if(note.trim())void run(async()=>{const result=await api.addNote(projectId,taskId,note.trim());setNote('');return result;});}}><label htmlFor="new-note">Add note</label><textarea id="new-note" value={note} onChange={e=>setNote(e.target.value)}/><button disabled={!note.trim()}>Add note</button></form>}</article>
    <article className="card"><span className="card-title">Activity history</span>{detail.activity.length===0?<p className="hint">No task activity yet.</p>:<ul className="roadmap-activity">{detail.activity.map(entry=><li key={entry.id}><span>{entry.label}</span><time dateTime={entry.occurredAt}>{new Date(entry.occurredAt).toLocaleString()}</time></li>)}</ul>}</article>
  </section>;
}

function TaskEdit({detail,busy,onSave}:{detail:TaskDetailResponse;busy:boolean;onSave:(body:any)=>Promise<void>}){const [title,setTitle]=useState(detail.task.title);const [description,setDescription]=useState(detail.task.description);const [priority,setPriority]=useState(detail.task.priority);const [nextAction,setNextAction]=useState(detail.task.nextAction);return <form className="roadmap-form" onSubmit={e=>{e.preventDefault();void onSave({title:title.trim(),description,priority,nextAction});}}><div className="field"><label htmlFor="task-title">Title</label><input id="task-title" required value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field"><label htmlFor="task-description">Description</label><textarea id="task-description" value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="field"><label htmlFor="task-next-action">Next action</label><textarea id="task-next-action" value={nextAction} onChange={e=>setNextAction(e.target.value)} placeholder="Write the next manual action"/></div><div className="field"><label htmlFor="task-priority">Priority</label><select id="task-priority" value={priority} onChange={e=>setPriority(e.target.value as RoadmapPriority)}>{priorities.map(p=><option key={p}>{p}</option>)}</select></div><button className="primary" disabled={busy||!title.trim()}>Save task details</button></form>}
