import { randomUUID } from 'node:crypto';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { hashPassword } from '../../src/auth/password.js';
import { createHarness, dockerAvailable, readCookie, type TestHarness } from './helpers.js';
import { createMilestone as createMilestoneInStore } from '../../src/roadmap/store.js';

const hasDocker=await dockerAvailable();let harness:TestHarness;
const email='roadmap@example.test',password='a-secure-roadmap-test-password';
let auth:{token:string;csrfToken:string};
let actorId:string;
const request=(method:string,url:string,payload?:unknown)=>harness.app.inject({method,url,...(payload!==undefined?{payload}:{}),cookies:{pc_session:auth.token},headers:{'x-csrf-token':auth.csrfToken}});
async function project(status='active'){
  const id=randomUUID();await harness.ctx.db.query(`INSERT INTO projects(id,name,status,archived_at,location_input_path,location_canonical_path,location_allowed_root,created_by) VALUES($1,$2,$3,CASE WHEN $3='archived' THEN now() END,$4,$4,'/tmp',$5)`,[id,`Roadmap ${id.slice(0,6)}`,status,`/tmp/${id}`,null]);return id;
}
async function milestone(projectId:string,title='Milestone'){
  const response=await request('POST',`/api/projects/${projectId}/roadmap/milestones`,{title});expect(response.statusCode).toBe(201);return response.json().milestones.at(-1).id as string;
}
async function task(projectId:string,milestoneId:string,title='Task'){
  const response=await request('POST',`/api/projects/${projectId}/roadmap/milestones/${milestoneId}/tasks`,{title});expect(response.statusCode).toBe(201);return response.json().detail.task.id as string;
}

describe.skipIf(!hasDocker)('manual roadmap',()=>{
  beforeAll(async()=>{harness=await createHarness();actorId=(await harness.ctx.db.query<{id:string}>('INSERT INTO users(email,display_name,password_hash,role) VALUES($1,$2,$3,\'admin\') RETURNING id',[email,'Roadmap Tester',await hashPassword(password)])).rows[0]!.id;const login=await harness.app.inject({method:'POST',url:'/api/auth/login',payload:{email,password},remoteAddress:'10.88.0.1'});auth={token:readCookie(login.headers['set-cookie'],'pc_session')!,csrfToken:login.json().csrfToken};},120_000);
  afterAll(async()=>harness?.teardown());

  it('requires authentication for roadmap reads',async()=>{const id=await project();const response=await harness.app.inject({method:'GET',url:`/api/projects/${id}/roadmap`});expect(response.statusCode).toBe(401);});

  it('creates milestones and tasks and derives safe progress',async()=>{const id=await project();const m=await milestone(id);const t=await task(id,m);let roadmap=(await request('GET',`/api/projects/${id}/roadmap`)).json();expect(roadmap.progress).toEqual({completed:0,total:1,percentage:0});expect(roadmap.milestones[0].progress.total).toBe(1);await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'in_progress'});await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'done'});roadmap=(await request('GET',`/api/projects/${id}/roadmap`)).json();expect(roadmap.progress).toEqual({completed:1,total:1,percentage:100});await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'planned'});expect((await request('GET',`/api/projects/${id}/roadmap/tasks/${t}`)).json().detail.task.completedAt).toBeNull();});

  it('excludes cancelled tasks from the denominator and handles zero tasks',async()=>{const id=await project();const empty=await milestone(id,'Empty');const m=await milestone(id,'Work');const t=await task(id,m);await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'cancelled'});const roadmap=(await request('GET',`/api/projects/${id}/roadmap`)).json();expect(roadmap.progress).toEqual({completed:0,total:0,percentage:0});expect(roadmap.milestones.find((x:any)=>x.id===empty).progress).toEqual({completed:0,total:0,percentage:0});});

  it('requires block reasons, preserves redacted history, and records timestamps',async()=>{const id=await project();const m=await milestone(id);const t=await task(id,m);expect((await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'blocked'})).statusCode).toBe(422);const blocked=await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'blocked',blockedReason:'password=hunter2 waiting for credentials'});expect(blocked.statusCode).toBe(200);expect(blocked.json().detail.task.blockedReason).toContain('hunter2');const started=await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'in_progress'});expect(started.json().detail.task.startedAt).toBeTruthy();expect(started.json().detail.task.blockedReason).toBeNull();const history=(await request('GET',`/api/projects/${id}/roadmap/tasks/${t}`)).json().detail.activity;expect(history.some((entry:any)=>entry.label.includes('password=[redacted]'))).toBe(true);expect(JSON.stringify(history)).not.toContain('hunter2');});

  it('requires explicit acceptance override and audits without criterion text',async()=>{const id=await project();const m=await milestone(id);const t=await task(id,m);await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/criteria`,{text:'SECRET_VALUE_should_not_be_in_audit'});const warning=await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'in_progress'});expect(warning.statusCode).toBe(200);const confirm=await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'done'});expect(confirm.statusCode).toBe(409);expect(confirm.json().error.confirmation).toEqual({kind:'incomplete_acceptance',count:1});const done=await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'done',acknowledgeIncompleteAcceptance:true});expect(done.statusCode).toBe(200);const auditRows=await harness.ctx.db.query('SELECT detail::text FROM audit_events WHERE detail->>\'taskId\'=$1',[t]);expect(auditRows.rows.map(r=>r.detail).join(' ')).not.toContain('SECRET_VALUE');});

  it('rejects self, duplicate, cross-project and circular dependencies',async()=>{const id=await project();const m=await milestone(id);const a=await task(id,m,'A'),b=await task(id,m,'B'),c=await task(id,m,'C');expect((await request('POST',`/api/projects/${id}/roadmap/tasks/${a}/dependencies`,{dependsOnTaskId:a})).statusCode).toBe(409);expect((await request('POST',`/api/projects/${id}/roadmap/tasks/${b}/dependencies`,{dependsOnTaskId:a})).statusCode).toBe(201);expect((await request('POST',`/api/projects/${id}/roadmap/tasks/${b}/dependencies`,{dependsOnTaskId:a})).statusCode).toBe(409);expect((await request('POST',`/api/projects/${id}/roadmap/tasks/${c}/dependencies`,{dependsOnTaskId:b})).statusCode).toBe(201);expect((await request('POST',`/api/projects/${id}/roadmap/tasks/${a}/dependencies`,{dependsOnTaskId:c})).statusCode).toBe(409);const other=await project();const om=await milestone(other);const foreign=await task(other,om);expect((await request('POST',`/api/projects/${id}/roadmap/tasks/${a}/dependencies`,{dependsOnTaskId:foreign})).statusCode).toBe(404);});

  it('serializes concurrent dependency edges so they cannot form a cycle',async()=>{const id=await project();const m=await milestone(id);const a=await task(id,m,'A'),b=await task(id,m,'B');const responses=await Promise.all([request('POST',`/api/projects/${id}/roadmap/tasks/${a}/dependencies`,{dependsOnTaskId:b}),request('POST',`/api/projects/${id}/roadmap/tasks/${b}/dependencies`,{dependsOnTaskId:a})]);expect(responses.map(r=>r.statusCode).sort()).toEqual([201,409]);});

  it('requires dependency override before starting',async()=>{const id=await project();const m=await milestone(id);const a=await task(id,m,'A'),b=await task(id,m,'B');await request('POST',`/api/projects/${id}/roadmap/tasks/${b}/dependencies`,{dependsOnTaskId:a});const warning=await request('POST',`/api/projects/${id}/roadmap/tasks/${b}/status`,{status:'in_progress'});expect(warning.statusCode).toBe(409);expect(warning.json().error.confirmation).toEqual({kind:'incomplete_dependencies',count:1});expect((await request('POST',`/api/projects/${id}/roadmap/tasks/${b}/status`,{status:'in_progress',acknowledgeIncompleteDependencies:true})).statusCode).toBe(200);const override=await harness.ctx.db.query("SELECT 1 FROM audit_events WHERE event_type='roadmap.dependency.override' AND detail->>'taskId'=$1",[b]);expect(override.rowCount).toBe(1);});

  it('keeps reorder positions dense at boundaries',async()=>{const id=await project();const a=await milestone(id,'A'),b=await milestone(id,'B');expect((await request('POST',`/api/projects/${id}/roadmap/milestones/${a}/reorder`,{direction:'up'})).statusCode).toBe(200);await request('POST',`/api/projects/${id}/roadmap/milestones/${b}/reorder`,{direction:'up'});const rows=await harness.ctx.db.query('SELECT id,sort_order FROM roadmap_milestones WHERE project_id=$1 ORDER BY sort_order',[id]);expect(rows.rows).toEqual([{id:b,sort_order:0},{id:a,sort_order:1}]);});

  it('supports criteria and notes CRUD while keeping note bodies out of audit',async()=>{const id=await project();const m=await milestone(id);const t=await task(id,m);let detail=(await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/criteria`,{text:'Criterion'})).json().detail;const criterion=detail.criteria[0].id;detail=(await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/criteria/${criterion}/completion`,{isCompleted:true})).json().detail;expect(detail.criteria[0].isCompleted).toBe(true);detail=(await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/notes`,{body:'TOP_SECRET_NOTE'})).json().detail;const note=detail.notes[0].id;await request('PATCH',`/api/projects/${id}/roadmap/tasks/${t}/notes/${note}`,{body:'UPDATED_SECRET_NOTE'});detail=(await request('DELETE',`/api/projects/${id}/roadmap/tasks/${t}/notes/${note}`)).json().detail;expect(detail.notes).toHaveLength(0);const audit=await harness.ctx.db.query('SELECT detail::text FROM audit_events WHERE detail->>\'noteId\'=$1',[note]);expect(audit.rows.map(r=>r.detail).join(' ')).not.toMatch(/SECRET_NOTE/);});

  it('makes an archived project roadmap read-only and preserves it after reactivation',async()=>{const id=await project();const m=await milestone(id);await task(id,m);await request('POST',`/api/projects/${id}/archive`);const read=await request('GET',`/api/projects/${id}/roadmap`);expect(read.statusCode).toBe(200);expect(read.json().readOnly).toBe(true);expect((await request('POST',`/api/projects/${id}/roadmap/milestones`,{title:'Denied'})).statusCode).toBe(409);await request('POST',`/api/projects/${id}/reactivate`);expect((await request('GET',`/api/projects/${id}/roadmap`)).json().milestones).toHaveLength(1);});

  it('makes archived and cancelled milestones read-only until reactivated or reopened',async()=>{const id=await project();const m=await milestone(id);const t=await task(id,m);await request('POST',`/api/projects/${id}/roadmap/milestones/${m}/archive`);expect((await request('PATCH',`/api/projects/${id}/roadmap/tasks/${t}`,{nextAction:'Denied'})).statusCode).toBe(409);expect((await request('POST',`/api/projects/${id}/roadmap/milestones/${m}/reorder`,{direction:'up'})).statusCode).toBe(409);await request('POST',`/api/projects/${id}/roadmap/milestones/${m}/reactivate`);expect((await request('PATCH',`/api/projects/${id}/roadmap/tasks/${t}`,{nextAction:'Allowed'})).statusCode).toBe(200);await request('POST',`/api/projects/${id}/roadmap/milestones/${m}/status`,{status:'cancelled'});expect((await request('PATCH',`/api/projects/${id}/roadmap/tasks/${t}`,{nextAction:'Denied again'})).statusCode).toBe(409);expect((await request('POST',`/api/projects/${id}/roadmap/milestones/${m}/reorder`,{direction:'up'})).statusCode).toBe(409);await request('POST',`/api/projects/${id}/roadmap/milestones/${m}/status`,{status:'planned'});expect((await request('GET',`/api/projects/${id}/roadmap/tasks/${t}`)).json().detail.task.nextAction).toBe('Allowed');});

  it('keeps lifecycle timestamps stable on repeated same-state requests',async()=>{const id=await project();const m=await milestone(id);const t=await task(id,m);await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'in_progress'});let detail=(await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'done'})).json().detail;const completedAt=detail.task.completedAt;detail=(await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/status`,{status:'done'})).json().detail;expect(detail.task.completedAt).toBe(completedAt);detail=(await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/criteria`,{text:'Stable'})).json().detail;const criterion=detail.criteria[0];detail=(await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/criteria/${criterion.id}/completion`,{isCompleted:true})).json().detail;const criterionCompletedAt=detail.criteria[0].completedAt;detail=(await request('POST',`/api/projects/${id}/roadmap/tasks/${t}/criteria/${criterion.id}/completion`,{isCompleted:true})).json().detail;expect(detail.criteria[0].completedAt).toBe(criterionCompletedAt);});

  it('does not grant physical DELETE on milestones or tasks',async()=>{const id=await project();const m=await milestone(id);const t=await task(id,m);await expect(harness.ctx.db.query('DELETE FROM roadmap_tasks WHERE id=$1',[t])).rejects.toMatchObject({code:'42501'});await expect(harness.ctx.db.query('DELETE FROM roadmap_milestones WHERE id=$1',[m])).rejects.toMatchObject({code:'42501'});});

  it('grants backup_reader read-only access to every roadmap table',async()=>{const tables=['roadmap_milestones','roadmap_tasks','task_acceptance_criteria','task_dependencies','task_notes'];for(const table of tables){const result=await harness.ctx.db.query<{can_read:boolean;can_write:boolean}>(`SELECT has_table_privilege('backup_reader',$1,'SELECT') can_read, has_table_privilege('backup_reader',$1,'INSERT,UPDATE,DELETE') can_write`,[table]);expect(result.rows[0]).toEqual({can_read:true,can_write:false});}});

  it('rolls the mutation back when required audit fails',async()=>{const id=await project();await expect(createMilestoneInStore(harness.ctx.db,id,actorId,{title:'Must rollback',description:'',status:'planned',priority:'medium'},async()=>{throw new Error('audit unavailable');})).rejects.toThrow('audit unavailable');const rows=await harness.ctx.db.query('SELECT 1 FROM roadmap_milestones WHERE project_id=$1',[id]);expect(rows.rowCount).toBe(0);});
});
